[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.6",
    "msal>=1.33.0",
    "pdfplumber>=0.11.7",
    "requests>=2.32.4",
    "selenium>=4.34.2",
    "watchdog>=6.0.0",
]
